feat: integration tests - add action for posting test trigger comment on PR, add separate action for image builds on PR updates

diff --git a/.github/workflows/build-push-images-on-pr-update.yaml b/.github/workflows/build-push-images-on-pr-update.yaml
--- a/.github/workflows/build-push-images-on-pr-update.yaml
+++ b/.github/workflows/build-push-images-on-pr-update.yaml
@@ -1,7 +1,15 @@
-name: Build Catalog FBC and run Integration tests
+name: Build and push operator images on PR update
 on:
   pull_request_target:
-    types: [labeled]
+    types: [ opened, synchronize, reopened ]
+    paths:
+      - 'bundle/**'
+      - 'cmd/**'
+      - 'config/**'
+      - 'Dockerfiles/**'
+      - 'internal/**'
+      - 'pkg/**'
+      - 'cmd/main.go'
 
 permissions: { }
 
@@ -10,14 +18,17 @@ env:
   PR_NUMBER: pr-${{ github.event.number }}
 jobs:
   get-merge-commit:
+    # runs on every PR update, unless 'run-integration-tests' label is present
+    # done to prevent potentially conflicting image builds between this action and the integration test action
+    if: (!contains(github.event.pull_request.labels.*.name, 'run-integration-tests'))
     name: Get merge commit
     uses: ./.github/workflows/get-merge-commit.yaml
 
   create-catalog-image:
     name: Build/push catalog image
-    # add this condition to the jenkins job step -> if: ${{ github.event.label.name == 'run-integration-tests' }}
     runs-on: ubuntu-latest
     needs: get-merge-commit
+    if: (!contains(github.event.pull_request.labels.*.name, 'run-integration-tests'))
     env:
       IMAGE_BUILDER: podman
     steps:
@@ -49,25 +60,34 @@ jobs:
         env:
           OPERATOR_REPOSITORY_NAME: opendatahub-io/opendatahub-operator
         run: |
-          version_tag=$(curl -s https://api.github.com/repos/${OPERATOR_REPOSITORY_NAME}/releases/latest | jq -r .tag_name)-${{ env.PR_NUMBER }}
+          raw_version_tag=$(curl -s https://api.github.com/repos/${OPERATOR_REPOSITORY_NAME}/releases/latest | jq -r .tag_name)
+
+          if [ -z "$raw_version_tag" ] || [ "$raw_version_tag" == "null" ]; then
+            echo "Failed to retrieve a valid release tag from ${{ env.OPERATOR_REPOSITORY_NAME }}, API call failed. Please re-run the action if possible."
+            exit 1
+          fi
+          echo "Latest ODH version '${raw_version_tag}' obtained successfully."
+
+          version_tag=$raw_version_tag-${{ env.PR_NUMBER }}
+          echo "Proceeding to use version tag '${version_tag}' in the operator and bundle image builds."
           echo "VERSION_TAG=${version_tag:1}" >> $GITHUB_ENV
 
       - name: Create operator image
         if: needs.get-merge-commit.outputs.mergedSha
         env:
-          IMG: ${{ env.IMAGE_TAG_BASE }}:v${VERSION_TAG}
+          IMG: ${{ env.IMAGE_TAG_BASE }}:v${{ env.VERSION_TAG }}
         run: |
-          echo "version tag: ${VERSION_TAG}"
+          echo "version tag: ${{ env.VERSION_TAG }}"
           make image
 
       - name: Create bundle image
         if: needs.get-merge-commit.outputs.mergedSha
         env:
-          BUNDLE_IMG: ${{ env.IMAGE_TAG_BASE }}-bundle:v${VERSION_TAG}
-          IMG_TAG: v${VERSION_TAG}
-          VERSION: ${VERSION_TAG}
+          BUNDLE_IMG: ${{ env.IMAGE_TAG_BASE }}-bundle:v${{ env.VERSION_TAG }}
+          IMG_TAG: v${{ env.VERSION_TAG }}
+          VERSION: ${{ env.VERSION_TAG }}
         run: |
-          echo "version tag: ${VERSION_TAG}"
+          echo "version tag: ${{ env.VERSION_TAG }}"
           make bundle-build
           make bundle-push
 
@@ -75,8 +95,8 @@ jobs:
         if: needs.get-merge-commit.outputs.mergedSha
         env:
           CATALOG_IMG: ${{ env.IMAGE_TAG_BASE }}-catalog:${{ env.PR_NUMBER }}
-          BUNDLE_IMG: ${{ env.IMAGE_TAG_BASE }}-bundle:v${VERSION_TAG}
+          BUNDLE_IMG: ${{ env.IMAGE_TAG_BASE }}-bundle:v${{ env.VERSION_TAG }}
         run: |
-          echo "version tag: ${VERSION_TAG}"
+          echo "version tag: ${{ env.VERSION_TAG }}"
           make catalog-build 
           make catalog-push
